///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace IOT_Telemedicine_System
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the IOT_Telemedicine_SystemRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c4b54dc4-35ef-4cc9-83a1-1666a7ed031b")]
    public partial class IOT_Telemedicine_SystemRepository : RepoGenBaseFolder
    {
        static IOT_Telemedicine_SystemRepository instance = new IOT_Telemedicine_SystemRepository();
        IOT_Telemedicine_SystemRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        IOT_Telemedicine_SystemRepositoryFolders.ExplorerAppFolder _explorer;
        IOT_Telemedicine_SystemRepositoryFolders.LoginV8AppFolder _loginv8;
        IOT_Telemedicine_SystemRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the IOT_Telemedicine_SystemRepository element repository.
        /// </summary>
        [RepositoryFolder("c4b54dc4-35ef-4cc9-83a1-1666a7ed031b")]
        public static IOT_Telemedicine_SystemRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public IOT_Telemedicine_SystemRepository() 
            : base("IOT_Telemedicine_SystemRepository", "/", null, 0, false, "c4b54dc4-35ef-4cc9-83a1-1666a7ed031b", ".\\RepositoryImages\\IOT_Telemedicine_SystemRepositoryc4b54dc4.rximgres")
        {
            _applicationundertest = new IOT_Telemedicine_SystemRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new IOT_Telemedicine_SystemRepositoryFolders.ExplorerAppFolder(this);
            _loginv8 = new IOT_Telemedicine_SystemRepositoryFolders.LoginV8AppFolder(this);
            _dropdown = new IOT_Telemedicine_SystemRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c4b54dc4-35ef-4cc9-83a1-1666a7ed031b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("30901cf4-3669-4ff8-bd5b-6b98b8130f4e")]
        public virtual IOT_Telemedicine_SystemRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("5e93c9c0-cf4b-4428-93cc-d16cc2fff871")]
        public virtual IOT_Telemedicine_SystemRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The LoginV8 folder.
        /// </summary>
        [RepositoryFolder("f471f202-e084-4a82-ad6f-857f1515e230")]
        public virtual IOT_Telemedicine_SystemRepositoryFolders.LoginV8AppFolder LoginV8
        {
            get { return _loginv8; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("bd5f706f-4248-483c-b418-d5a5cee33290")]
        public virtual IOT_Telemedicine_SystemRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class IOT_Telemedicine_SystemRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("30901cf4-3669-4ff8-bd5b-6b98b8130f4e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='http://localhost:8080/IOT_T_M/Login.jsp']", parentFolder, 30000, null, false, "30901cf4-3669-4ff8-bd5b-6b98b8130f4e", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("30901cf4-3669-4ff8-bd5b-6b98b8130f4e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("30901cf4-3669-4ff8-bd5b-6b98b8130f4e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("5e93c9c0-cf4b-4428-93cc-d16cc2fff871")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechrome1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "5e93c9c0-cf4b-4428-93cc-d16cc2fff871", "")
            {
                _googlechrome1runningwindowInfo = new RepoItemInfo(this, "GoogleChrome1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[10]", 30000, null, "c0ee9773-1ed0-4c3e-bb99-c97c82135001");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e93c9c0-cf4b-4428-93cc-d16cc2fff871")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e93c9c0-cf4b-4428-93cc-d16cc2fff871")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item.
            /// </summary>
            [RepositoryItem("c0ee9773-1ed0-4c3e-bb99-c97c82135001")]
            public virtual Ranorex.Button GoogleChrome1RunningWindow
            {
                get
                {
                    return _googlechrome1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("c0ee9773-1ed0-4c3e-bb99-c97c82135001")]
            public virtual RepoItemInfo GoogleChrome1RunningWindowInfo
            {
                get
                {
                    return _googlechrome1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The LoginV8AppFolder folder.
        /// </summary>
        [RepositoryFolder("f471f202-e084-4a82-ad6f-857f1515e230")]
        public partial class LoginV8AppFolder : RepoGenBaseFolder
        {
            IOT_Telemedicine_SystemRepositoryFolders.HttpLocalhost8080IOTTMLogin1Folder _httplocalhost8080iottmlogin1;
            RepoItemInfo _personInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new LoginV8  folder.
            /// </summary>
            public LoginV8AppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginV8", "/dom[@domain='localhost:8080']", parentFolder, 30000, null, false, "f471f202-e084-4a82-ad6f-857f1515e230", "")
            {
                _httplocalhost8080iottmlogin1 = new IOT_Telemedicine_SystemRepositoryFolders.HttpLocalhost8080IOTTMLogin1Folder(this);
                _personInfo = new RepoItemInfo(this, "Person", ".//a[#'navbarDropdownProfile']/i[@innertext='person']", 30000, null, "dd66937c-4211-4395-850f-629f0a5039c2");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "body/div/?/?/nav//ul//a[@innertext='Log out']", 30000, null, "53d080be-514c-4261-89f4-7f6159ae5771");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f471f202-e084-4a82-ad6f-857f1515e230")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f471f202-e084-4a82-ad6f-857f1515e230")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Person item.
            /// </summary>
            [RepositoryItem("dd66937c-4211-4395-850f-629f0a5039c2")]
            public virtual Ranorex.ITag Person
            {
                get
                {
                    return _personInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The Person item info.
            /// </summary>
            [RepositoryItemInfo("dd66937c-4211-4395-850f-629f0a5039c2")]
            public virtual RepoItemInfo PersonInfo
            {
                get
                {
                    return _personInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("53d080be-514c-4261-89f4-7f6159ae5771")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("53d080be-514c-4261-89f4-7f6159ae5771")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The HttpLocalhost8080IOTTMLogin1 folder.
            /// </summary>
            [RepositoryFolder("55cc85fc-baa1-4180-8753-3c66c3fa7132")]
            public virtual IOT_Telemedicine_SystemRepositoryFolders.HttpLocalhost8080IOTTMLogin1Folder HttpLocalhost8080IOTTMLogin1
            {
                get { return _httplocalhost8080iottmlogin1; }
            }
        }

        /// <summary>
        /// The HttpLocalhost8080IOTTMLogin1Folder folder.
        /// </summary>
        [RepositoryFolder("55cc85fc-baa1-4180-8753-3c66c3fa7132")]
        public partial class HttpLocalhost8080IOTTMLogin1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _httplocalhost8080iottmloginInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passInfo;
            RepoItemInfo _buttontagsigninInfo;

            /// <summary>
            /// Creates a new HttpLocalhost8080IOTTMLogin1  folder.
            /// </summary>
            public HttpLocalhost8080IOTTMLogin1Folder(RepoGenBaseFolder parentFolder) :
                    base("HttpLocalhost8080IOTTMLogin1", "body/div//form[@action='http://localhost:8080/IOT_T_M/login']", parentFolder, 30000, null, false, "55cc85fc-baa1-4180-8753-3c66c3fa7132", "")
            {
                _httplocalhost8080iottmloginInfo = new RepoItemInfo(this, "HttpLocalhost8080IOTTMLogin", "", 30000, null, "ae76a7d0-f165-4d33-8786-42cbb07a163c");
                _usernameInfo = new RepoItemInfo(this, "Username", "div[1]/input[@name='username']", 30000, null, "236cdc4d-718f-4575-b4a4-1508b8583694");
                _passInfo = new RepoItemInfo(this, "Pass", "div[2]/input[@name='pass']", 30000, null, "7521beff-c73f-4620-ad7b-89423f0bff50");
                _buttontagsigninInfo = new RepoItemInfo(this, "ButtonTagSignIn", "div[4]/button[@innertext='Sign in']", 30000, null, "42374218-f8bb-4f65-ba32-5ec05df120b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55cc85fc-baa1-4180-8753-3c66c3fa7132")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55cc85fc-baa1-4180-8753-3c66c3fa7132")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpLocalhost8080IOTTMLogin item.
            /// </summary>
            [RepositoryItem("ae76a7d0-f165-4d33-8786-42cbb07a163c")]
            public virtual Ranorex.FormTag HttpLocalhost8080IOTTMLogin
            {
                get
                {
                    return _httplocalhost8080iottmloginInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The HttpLocalhost8080IOTTMLogin item info.
            /// </summary>
            [RepositoryItemInfo("ae76a7d0-f165-4d33-8786-42cbb07a163c")]
            public virtual RepoItemInfo HttpLocalhost8080IOTTMLoginInfo
            {
                get
                {
                    return _httplocalhost8080iottmloginInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("236cdc4d-718f-4575-b4a4-1508b8583694")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("236cdc4d-718f-4575-b4a4-1508b8583694")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Pass item.
            /// </summary>
            [RepositoryItem("7521beff-c73f-4620-ad7b-89423f0bff50")]
            public virtual Ranorex.InputTag Pass
            {
                get
                {
                    return _passInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Pass item info.
            /// </summary>
            [RepositoryItemInfo("7521beff-c73f-4620-ad7b-89423f0bff50")]
            public virtual RepoItemInfo PassInfo
            {
                get
                {
                    return _passInfo;
                }
            }

            /// <summary>
            /// The ButtonTagSignIn item.
            /// </summary>
            [RepositoryItem("42374218-f8bb-4f65-ba32-5ec05df120b9")]
            public virtual Ranorex.ButtonTag ButtonTagSignIn
            {
                get
                {
                    return _buttontagsigninInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagSignIn item info.
            /// </summary>
            [RepositoryItemInfo("42374218-f8bb-4f65-ba32-5ec05df120b9")]
            public virtual RepoItemInfo ButtonTagSignInInfo
            {
                get
                {
                    return _buttontagsigninInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("bd5f706f-4248-483c-b418-d5a5cee33290")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "bd5f706f-4248-483c-b418-d5a5cee33290", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd5f706f-4248-483c-b418-d5a5cee33290")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd5f706f-4248-483c-b418-d5a5cee33290")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
