///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IOT_Telemedicine_System
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("e8f519ba-2fb1-405e-9236-7f0f0f1e7bc8", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IOT_Telemedicine_SystemRepository repository.
        /// </summary>
        public static IOT_Telemedicine_SystemRepository repo = IOT_Telemedicine_SystemRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.GoogleChrome1RunningWindow' at 16;14.", repo.Explorer.GoogleChrome1RunningWindowInfo, new RecordItemIndex(0));
            repo.Explorer.GoogleChrome1RunningWindow.Click("16;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginV8.HttpLocalhost8080IOTTMLogin1.Username' at 166;41.", repo.LoginV8.HttpLocalhost8080IOTTMLogin1.UsernameInfo, new RecordItemIndex(1));
            repo.LoginV8.HttpLocalhost8080IOTTMLogin1.Username.Click("166;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 143;25.", repo.Dropdown.SelfInfo, new RecordItemIndex(2));
            repo.Dropdown.Self.Click("143;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginV8.HttpLocalhost8080IOTTMLogin1.Pass' at 124;34.", repo.LoginV8.HttpLocalhost8080IOTTMLogin1.PassInfo, new RecordItemIndex(3));
            repo.LoginV8.HttpLocalhost8080IOTTMLogin1.Pass.Click("124;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginV8.HttpLocalhost8080IOTTMLogin1.HttpLocalhost8080IOTTMLogin' at 459;251.", repo.LoginV8.HttpLocalhost8080IOTTMLogin1.HttpLocalhost8080IOTTMLoginInfo, new RecordItemIndex(4));
            repo.LoginV8.HttpLocalhost8080IOTTMLogin1.HttpLocalhost8080IOTTMLogin.Click("459;251");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginV8.HttpLocalhost8080IOTTMLogin1.ButtonTagSignIn' at 254;18.", repo.LoginV8.HttpLocalhost8080IOTTMLogin1.ButtonTagSignInInfo, new RecordItemIndex(5));
            repo.LoginV8.HttpLocalhost8080IOTTMLogin1.ButtonTagSignIn.Click("254;18");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
